name = "dplib"
version = "0.1.0"
defaultTargets = ["DPLib"]
lintDriver = "batteries/runLinter"

[leanOptions]
weak.linter.mathlibStandardSet = true
weak.linter.flexible = true
weak.linter.pythonStyle = false
weak.linter.checkInitImports = false
weak.linter.allScriptsDocumented = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0-rc2"

[[lean_lib]]
name = "DPLib"
globs = ["DPLib.*"]